const STORAGE_NAMESPACES = {
  PRIMARY_KEYWORDS: 'PRIMARY_KEYWORDS',
  SECONDARY_KEYWORDS: 'SECONDARY_KEYWORDS',
  EXCLUSION_KEYWORDS: 'EXCLUSION_KEYWORDS',
  API_KEY: 'API_KEY',
  JOB_INFOS: 'JOB_INFOS'
};

export default STORAGE_NAMESPACES;